version: '3.8'

services:
  redis-geo:
    image: redis:7
    container_name: redis-geo
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - taxinet
    ports:
      - "6379:6379"

  redis-matching:
    image: redis:7
    container_name: redis-matching
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - taxinet
    ports:
      - "6380:6379"
      
  geo-service:
    container_name: geo-service
    build: 
      context: ./services/geo
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/geo:/app 
    environment:
      APP_PORT: ":8081"
      GEO_REDIS_HOST: redis-geo
      GEO_REDIS_PORT: 6379
    depends_on:
      - redis-geo
    networks:
      - taxinet
    ports:
      - "8081:8081"
    command: ["air"]

  matching-service:
    container_name: matching-service
    build:
      context: ./services/matching
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/matching:/app
    environment:
      APP_PORT: ":9090"
      GEO_SERVICE_URL: "geo-service:8081"
      MATCHING_REDIS_HOST: redis-matching
      MATCHIG_REDIS_PORT: 6379
    depends_on:
      - geo-service
      - redis-matching
    networks:
      - taxinet
    ports:
      - "9090:9090"
    command: ["air"]

  notification-service:
    container_name: notification-service
    build:
      context: ./services/notification
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/notification:/app
    environment:
      APP_PORT: ":8082"
    networks:
      - taxinet
    ports:
      - "8082:8082"
    command: ["air"]

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - taxinet
    ports:
      - "8123:8123"  
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD= 

  history-service:
    container_name: history-service
    build:
      context: ./services/history
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/history:/app
    environment:
      APP_PORT: ":8083"
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: "9000"
    depends_on:
      - clickhouse
    networks:
      - taxinet
    ports:
      - "8083:8083"
    command: ["air"]


volumes:
  redis_data:
  clickhouse_data:

networks:
  taxinet:
